--
ALTER TABLE	 [dbo].[supply_table]
ALTER COLUMN CSUSHPISA FLOAT

ALTER TABLE	 [dbo].[supply_table]
ALTER COLUMN MSACSR FLOAT

ALTER TABLE	 [dbo].[supply_table]
ALTER COLUMN PERMIT FLOAT

ALTER TABLE	[dbo].[supply_table] 
ALTER COLUMN TLRESCONS FLOAT

ALTER TABLE	 [dbo].[supply_table]
ALTER COLUMN EVACANTUSQ176N FLOAT
