ALTER TABLE	 supply_table
ALTER COLUMN CSUSHPISA FLOAT;

ALTER TABLE	 supply_table
ALTER COLUMN MSACSR FLOAT;

ALTER TABLE	 supply_table
ALTER COLUMN PERMIT FLOAT;

ALTER TABLE	 supply_table
ALTER COLUMN TLRESCONS FLOAT;

ALTER TABLE	 supply_table
ALTER COLUMN EVACANTUSQ176N FLOAT;
